DROP TABLE item_category CASCADE CONSTRAINTS;

DROP TABLE item CASCADE CONSTRAINTS;

DROP TABLE shop_order CASCADE CONSTRAINTS;

DROP TABLE user_account CASCADE CONSTRAINTS;

DROP TABLE employee_account CASCADE CONSTRAINTS;

DROP TABLE basket CASCADE CONSTRAINTS;

DROP TABLE order_contains_item CASCADE CONSTRAINTS;

CREATE TABLE item_category (
    category_id   INT
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY NOT NULL,
    category_name VARCHAR2(255) NOT NULL
);

CREATE TABLE item (
    item_id          INT
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY NOT NULL,
    item_name        VARCHAR2(255) NOT NULL,
    item_description CLOB,
    price            NUMBER(20, 2) NOT NULL,
    amount_in_stock  INTEGER NOT NULL,
    category_id      INTEGER
        REFERENCES item_category
    NOT NULL
);

-- user and employee accounts had a generalization in the original model,
-- the table "Person". Since the specialization is disjunct (no person can be
-- User and Employee at the same time - the small storage optimization of not storing
-- the name and email of a few people twice is not worth the added complexity),
-- and total (there can be no Person, which is not User, nor Employee), we decided
-- to simply include Person's attributes in User and Employee, and make them separate tables
CREATE TABLE user_account (
    personal_email VARCHAR2(255) PRIMARY KEY NOT NULL,
    first_name     NVARCHAR2(255) NOT NULL,
    last_name      NVARCHAR2(255) NOT NULL,
    username       NVARCHAR2(255) NOT NULL,
    password_hash  CHAR(64) NOT NULL,
    -- the following fields will not be required for user registration
    phone_number   VARCHAR2(15),
    street_name    VARCHAR2(128),
    city_name      VARCHAR2(128),
    zip_code       CHAR(5),
    CONSTRAINT user_pw_hash CHECK ( REGEXP_LIKE ( password_hash,
                                                  '^[0-9a-f]{64}$' ) ),
    CONSTRAINT user_zip_code CHECK ( REGEXP_LIKE ( zip_code,
                                                   '^\d{5}$' ) )
);

CREATE TABLE employee_account (
    personal_email VARCHAR2(255) PRIMARY KEY NOT NULL,
    first_name     NVARCHAR2(255) NOT NULL,
    last_name      NVARCHAR2(255) NOT NULL,
    username       NVARCHAR2(255) NOT NULL,
    password_hash  CHAR(64) NOT NULL,
    company_email  VARCHAR2(255) NOT NULL,
    salary         NUMBER(20, 2) NOT NULL,
    CONSTRAINT employee_pw_hash CHECK ( REGEXP_LIKE ( password_hash,
                                                      '^[0-9a-f]{64}$' ) )
);

CREATE TABLE shop_order (
    order_id              INT
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY NOT NULL,
    shipping_company      NVARCHAR2(255) NOT NULL,
    shipping_street_name  VARCHAR2(128) NOT NULL,
    shipping_city_name    VARCHAR2(128) NOT NULL,
    shipping_zip_code     CHAR(5) CHECK ( REGEXP_LIKE ( shipping_zip_code,
                                                    '^\d{5}$' ) ) NOT NULL,
    billing_street_name   VARCHAR2(128) NOT NULL,
    billing_city_name     VARCHAR2(128) NOT NULL,
    billing_zip_code      CHAR(5) CHECK ( REGEXP_LIKE ( billing_zip_code,
                                                   '^\d{5}$' ) ) NOT NULL,
    delivery_phone_number VARCHAR2(15),
    creation_date         TIMESTAMP DEFAULT current_timestamp NOT NULL,
    user_account          VARCHAR2(255)
        REFERENCES user_account ( personal_email )
    NOT NULL,
    employee_account      VARCHAR2(255)
        REFERENCES employee_account ( personal_email )
);

CREATE TABLE basket (
    personal_email
        REFERENCES user_account
    NOT NULL,
    item_id
        REFERENCES item
    NOT NULL,
    PRIMARY KEY ( personal_email,
                  item_id ),
    amount INTEGER NOT NULL
);

CREATE TABLE order_contains_item (
    item_id
        REFERENCES item
    NOT NULL,
    order_id
        REFERENCES shop_order
    NOT NULL,
    PRIMARY KEY ( item_id,
                  order_id ),
    amount INTEGER NOT NULL
);

-- insert example users

INSERT INTO user_account (
    personal_email,
    first_name,
    last_name,
    username,
    password_hash,
    phone_number,
    street_name,
    city_name,
    zip_code
) VALUES (
    'kentus@blentus.com',
    'Kentus',
    'Blentus',
    'kekel',
    '7253ec94b9ad29b292ad31664999e650b97cda5590407ff9c27cb589c7d7eef9',
    '666666666',
    'Kentusova',
    'Brnisko',
    '12757'
);

INSERT INTO user_account (
    personal_email,
    first_name,
    last_name,
    username,
    password_hash,
    phone_number,
    street_name,
    city_name,
    zip_code
) VALUES (
    'other@blentus.com',
    'Someone',
    'Else',
    'anotherone',
    '8e77b7602faa50484c5e9ef8ee6ab44e9c83ab6dc0bc30a6c5a078f0893efd78',
    '605123456',
    'Ulice 2',
    'Knowhere',
    '11234'
);

INSERT INTO user_account (
    personal_email,
    first_name,
    last_name,
    username,
    password_hash
) VALUES (
    'abc@def.com',
    'Abc',
    'Def',
    'abc',
    'bfd33f5eae21080b8b2cae7f7109cc7325107c04ad71573273d64beea063c067'
);

-- insert example employees

INSERT INTO employee_account (
    personal_email,
    first_name,
    last_name,
    username,
    password_hash,
    company_email,
    salary
) VALUES (
    'whatever@wherever.net',
    'name',
    'lastname',
    'employee1',
    '4f9c69753794e821cfd17646269689b7acc1e3be21e1ff62ba59bca06bd1e7b2',
    'employee1@koteseni.cz',
    12500.00
);

INSERT INTO employee_account (
    personal_email,
    first_name,
    last_name,
    username,
    password_hash,
    company_email,
    salary
) VALUES (
    'name@server.tld',
    'another',
    'last',
    'something',
    '3d5f44d8f5477011fc241cf602cb7c0f0bec0976f0d8dc7b8ad77733ada6ca7e',
    'employee2@koteseni.cz',
    62501.00
);

-- insert example item categories

INSERT INTO item_category ( category_name ) VALUES ( 'Smartphones' );

INSERT INTO item_category ( category_name ) VALUES ( 'Desktops' );

INSERT INTO item_category ( category_name ) VALUES ( 'Laptops' );

INSERT INTO item_category ( category_name ) VALUES ( 'Toasters' );

INSERT INTO item (
    item_name,
    item_description,
    price,
    amount_in_stock,
    category_id
) VALUES (
    'some phone',
    'this one has locked bootloader, you aint installing lineageos',
    14000.00,
    251,
    1 -- smartphones
);

INSERT INTO item (
    item_name,
    item_description,
    price,
    amount_in_stock,
    category_id
) VALUES (
    'another phone',
    'this one comes with apfelOS, you aint installing no apps on this one',
    42000.00,
    1532,
    1 -- smartphones
);

INSERT INTO item (
    item_name,
    item_description,
    price,
    amount_in_stock,
    category_id
) VALUES (
    'lonevo laptop 3000',
    'the keyboard will definitely not stop working after few years',
    22000.00,
    160,
    3 -- laptops
);

INSERT INTO item (
    item_name,
    item_description,
    price,
    amount_in_stock,
    category_id
) VALUES (
    'RGB gaming desktop 31',
    'you wont need any other lights in your home with this one',
    22000.00,
    160,
    2 -- desktops
);

INSERT INTO item (
    item_name,
    item_description,
    price,
    amount_in_stock,
    category_id
) VALUES (
    'TOTER 3000',
    'built-in discord moderation functionality',
    125000.00,
    12,
    4 -- toasters
);

-- insert example order

INSERT INTO shop_order (
    shipping_company,
    shipping_street_name,
    shipping_city_name,
    shipping_zip_code,
    billing_street_name,
    billing_city_name,
    billing_zip_code,
    delivery_phone_number,
    user_account
  )
VALUES
  (
    'Boxes S.R.O.',
    'Blue street',
    'Blue city',
    '04132',
    'Red street',
    'Red city',
    '23140',
    '666111000',
    'kentus@blentus.com'
  );

-- inserting items contained in orders

insert into order_contains_item (
    item_id,
    order_id,
    amount
) values (
    1, -- phone
    1,
    2
);

insert into order_contains_item (
    item_id,
    order_id,
    amount
) values (
    2,
    1,
    3
);

insert into order_contains_item (
    item_id,
    order_id,
    amount
) values (
    3,
    1,
    4
);

insert into order_contains_item (
    item_id,
    order_id,
    amount
) values (
    4,
    1,
    15
);

-- inserting items in user baskets

insert into basket (
    personal_email ,
    item_id,
    amount 
) values (
    'kentus@blentus.com',
    1, -- phone
    1
);

insert into basket (
    personal_email ,
    item_id,
    amount 
) values (
    'other@blentus.com',
    5, -- toaster
    1
);

insert into basket (
    personal_email ,
    item_id,
    amount 
) values (
    'other@blentus.com',
    3, -- laptop
    5
);
