# creates zip file ready for submission
zip:
	zip xbrabl04.zip uart_rx.vhd uart_rx_fsm.vhd zprava.pdf

# cleans all temporary build files
clean:
	rm -rf work *.s *.ghw *.cf xbrabl04.zip zprava.pdf synth.vhd
